version: "3.5"
services:
    tnmap-client:
        env_file: .env
        build:
            context: .
            dockerfile: ${DOCKERFILE}
        volumes:
            - .:/app
        restart: always
        networks:
            - api-network
        expose:
          - "3000"
        ports:
          - 3000:3000
networks:
    api-network:
        name: api-network
        external: true